"""Rebase Cole's air path and runway-end starts after a reviewed 200 m map patch.

Generate into scratch first; keep the real taxi junctions and supply stops fixed.
Usage: --after patched.fld --plan old_cole.txt --starts original.stp --out DIR
The analysis baseline describes the original Luavi revision, independent of line shifts.
"""
import argparse
import hashlib
import json
import math
import re
from pathlib import Path

from fld_geometry import FieldGeometry


SIGNS = {'Cole main 11/29':1, 'Cole secondary':1, 'Baluut':-1,
         'Sakhet 08/26':1, 'Mantaruun':-1, 'Dirt Strip':1, 'Highway Strip':0}
STARTS = {'[IFF1]BALUUT_RUNWAY':'Baluut', '[IFF4]SAKHET_RUNWAY':'Sakhet 08/26',
          '[IFF4]DIRT_STIP_RUWNAY':'Dirt Strip'}
TRAIN = {'TRAIN_COLE_29_':'Cole main 11/29', 'TRAIN_MANTURUUN_09_':'Mantaruun'}


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def resolve(field, baseline):
    rows = []
    for old in baseline['runways']:
        sign = SIGNS[old['name']]
        desired = old['safe_length']+abs(sign)*200
        expected = [old['center'][i]+sign*old['u'][i]*100 for i in range(2)]
        candidates = []
        for r in field.regions:
            if r['source'] != old['source'] or r['id'] != 1:
                continue
            dims = sorted([r['are'][2]-r['are'][0],r['are'][3]-r['are'][1]], reverse=True)
            if abs(dims[0]-desired)<.02 and abs(dims[1]-old['safe_width'])<.02:
                center = [sum(p[i] for p in r['points'])/4 for i in range(2)]
                candidates.append((math.dist(center,expected),r,center,dims))
        if not candidates or min(x[0] for x in candidates)>.1:
            raise ValueError(f'No independently matching extended region: {old["name"]}')
        _, region, center, dims = min(candidates,key=lambda x:x[0])
        delta = [2*(center[i]-old['center'][i]) for i in range(2)]
        matches = []
        for p in field.primitives:
            if p['source'] != old['source'] or p['file'] != old['pc2'] or p['primitive'] != old['primitive']:
                continue
            # These six runway cores are PLG; the unchanged highway is a QST.
            if sign and len(p['points'])!=4:
                continue
            if not sign:
                # All insertions are inside airport packs after this unchanged road.
                if p['draw_line']==old['drawing_line']:
                    matches.append(p)
                continue
            centroid = [sum(q[i] for q in p['points'])/len(p['points']) for i in range(2)]
            length = max(math.dist(a,b) for a,b in zip(p['points'],p['points'][1:]+p['points'][:1]))
            if abs(length-(old['visual_length']+200))<.05 and math.dist(centroid,expected)<25:
                matches.append(p)
        if len(matches)!=1:
            raise ValueError(f'Ambiguous/missing visible strip: {old["name"]}')
        rows.append(dict(name=old['name'],source=old['source'],region_line=region['line'],
            drawing_line=matches[0]['draw_line'],delta=delta,safe_length=dims[0],safe_width=dims[1]))
    return rows


def rebase_plan(path, output, cole):
    data = Path(path).read_text(encoding='utf-8').splitlines()
    delta = cole['delta']
    current = next(l.split() for l in data if l.startswith('RUNWAY '))
    if abs(float(current[4])+200-cole['safe_length'])>.1:
        raise ValueError('Plan is not the original pre-extension Cole plan')
    out = ['# Replay-derived Cole plan rebased for the 200 m runway extension.',
           '# Generated by tools/maps/rebase_runway_references.py; taxi/supply world positions retained.']
    i = 0
    shifted = connectors = 0
    while i<len(data):
        line = data[i]
        if line.startswith('RUNWAY '):
            p=line.split(' #',1)
            parts=p[0].split()
            parts[1]=f'{float(parts[1])+delta[0]:.2f}'
            parts[2]=f'{float(parts[2])+delta[1]:.2f}'
            parts[4]=f'{cole["safe_length"]:.1f}'
            line=' '.join(parts)+(' #'+p[1] if len(p)>1 else '')
        elif line.startswith('A '):
            parts=line.split()
            parts[1]=f'{float(parts[1])+delta[0]:.1f}'
            parts[2]=f'{float(parts[2])+delta[1]:.1f}'
            line=' '.join(parts)
            shifted+=1
        elif line.startswith('ROUTE ') and line.split()[2]=='IN':
            parts=line.split()
            count=int(parts[3])
            first=list(map(float,data[i+1].split()[1:4]))
            steps=math.ceil(math.hypot(*delta)/4)
            parts[3]=str(count+steps)
            out.append(' '.join(parts))
            for k in range(steps):
                f=1-k/steps
                out.append(f'R {first[0]+delta[0]*f:.1f} {first[1]+delta[1]*f:.1f} {first[2]:.1f}')
            connectors+=steps
            i+=1
            continue
        out.append(line)
        i+=1
    Path(output).write_text('\n'.join(out)+'\n',encoding='utf-8',newline='\n')
    return dict(air_points_shifted=shifted,straight_ground_connector_points=connectors,
                input_hash=sha(path),output_hash=sha(output),delta=delta)


def rebase_starts(path, output, rows):
    by_name={r['name']:r for r in rows}
    raw=Path(path).read_bytes()
    newline='\r\n' if b'\r\n' in raw else '\n'
    lines=raw.decode('latin-1').splitlines()
    name=None
    changed=[]
    for i,line in enumerate(lines):
        if line.startswith('N '):
            name=line[2:].strip()
        if not line.startswith('C POSITION '):
            continue
        site=STARTS.get(name)
        for prefix, candidate in TRAIN.items():
            if name and name.startswith(prefix):
                site=candidate
        if not site:
            continue
        parts=line.split()
        before=[float(v.removesuffix('m')) for v in parts[2:5]]
        delta=by_name[site]['delta']
        after=[before[0]+delta[0],before[1],before[2]+delta[1]]
        parts[2]=f'{after[0]:.2f}m'
        parts[4]=f'{after[2]:.2f}m'
        lines[i]=' '.join(parts)
        changed.append(dict(name=name,before=before,after=after))
    Path(output).write_bytes((newline.join(lines)+newline).encode('latin-1'))
    return dict(input_hash=sha(path),output_hash=sha(output),positions=changed)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--after',required=True,type=Path)
    parser.add_argument('--plan',required=True,type=Path)
    parser.add_argument('--starts',required=True,type=Path)
    parser.add_argument('--out',required=True,type=Path)
    parser.add_argument('--baseline',type=Path,default=Path('planning/data/luavi_runways_3km.json'))
    args=parser.parse_args()
    args.out.mkdir(parents=True,exist_ok=True)
    if args.out.resolve() in {args.plan.resolve().parent,args.starts.resolve().parent}:
        raise ValueError('Generate into scratch; do not overwrite live input files')
    baseline=json.loads(args.baseline.read_text())
    field=FieldGeometry(args.after)
    rows=resolve(field,baseline)
    cole=next(r for r in rows if r['name']=='Cole main 11/29')
    result=dict(map_hash=sha(args.after),plan=rebase_plan(args.plan,args.out/'cole_29.txt',cole),
        starts=rebase_starts(args.starts,args.out/'Luavi.stp',rows))
    (args.out/'anchors.json').write_text(json.dumps(rows,indent=2),encoding='utf-8')
    (args.out/'references.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
    print(f'Rebased {result["plan"]["air_points_shifted"]} air points and {len(result["starts"]["positions"])} starts')


if __name__=='__main__':
    main()
